Link: [The Basics](https://www.numpy.org.cn/en/user/quickstart.html#the-basics)

In [14]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

In [15]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
arr.shape    # the dimensions of the array.

(3, 5)

In [17]:
arr.size    # the total number of elements of the array.

15

In [18]:
arr.ndim    # the number of axes (dimensions) of the array.

2

In [19]:
arr.dtype    # an object describing the type of the elements in the array.

dtype('int64')

In [20]:
arr.itemsize    # the size in bytes of each element of the array.

8

In [21]:
arr.data    # the total number of elements of the array.